// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddProject'](arg1, arg2, arg3, arg4);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function UpdateProjectStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectStatus'](arg1, arg2);
}
