// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddPersona(arg1:string,arg2:string):Promise<number>;

export function AddProject(arg1:string,arg2:string,arg3:number,arg4:number):Promise<number>;

export function DeletePersona(arg1:number):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function GetAllPersonas():Promise<Array<models.Persona>>;

export function GetProjects():Promise<Array<models.Project>>;

export function UpdateProjectStatus(arg1:number,arg2:string):Promise<void>;
