// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPersona(arg1, arg2) {
  return window['go']['main']['App']['AddPersona'](arg1, arg2);
}

export function AddProject(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddProject'](arg1, arg2, arg3, arg4, arg5);
}

export function DeletePersona(arg1) {
  return window['go']['main']['App']['DeletePersona'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GetAllPersonas() {
  return window['go']['main']['App']['GetAllPersonas']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function ScanAndCache() {
  return window['go']['main']['App']['ScanAndCache']();
}

export function UpdateProjectStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectStatus'](arg1, arg2);
}
