// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {git} from '../models';

export function AddPersona(arg1:string,arg2:string):Promise<models.Persona>;

export function AddProject(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<models.Project>;

export function DeletePersona(arg1:number):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function GetAllPersonas():Promise<Array<models.Persona>>;

export function GetAllRepos():Promise<Array<models.DiscoveredRepos>>;

export function GetProjects():Promise<Array<models.Project>>;

export function ScanAndCache():Promise<Array<git.ScanResult>>;

export function UpdateProjectStatus(arg1:number,arg2:string):Promise<void>;
